### ISSUE TITLE
InActiveなオブジェクトでMantis LOD Editorの結果が反映されない

### ISSUE THREAD

**Issue by PancakeTorto1se** [hitsub/ndmf-mantis-lod-editor#3]
## 現象

* 例えばExpression Menuから出し入れするためにInActiveにしているGameObjectにNDMF Mantis LOD Editorをアタッチしても
ビルド、もしくは再生モードにした際にMantis LOD Editorの結果が反映されません。
  * なお、NDMF Mantis LOD Editorのプレビューは問題なく動作します。

## 環境

* NDMFMantisLODEditor v0.5.0
* Unity 2022.3.6f1
* Modular Avatar 1.9.7
* Non-Destructive Modular Framework 1.3.7

## 原因と思われる個所

* 以下の`GetComponentsInChildren`でInActiveなGameObjectが取得対象になっていないため、その後の処理が実行されない状態になっているようです。
  * https://github.com/hitsub/ndmf-mantis-lod-editor/blob/4a88c39137a0ed6d60e50926d33b295e1fd0230f/MantisLODEditor/NDMF/Editor/NDMFPlugin.cs#L21
* GetComponentsInChildrenに引数を追加し、`GetComponentsInChildren<NDMFMantisLODEditor>(true);`のようにすることでInActiveなGameObjectも取得対象になり、現象が発生しなくなります。

## 参考

* https://docs.unity3d.com/ScriptReference/GameObject.GetComponentsInChildren.html

**Comment by hitsub** [comment]
報告ありがとうございます！修正します
